"""Add Email field to User model

Revision ID: 908d9365a1b4
Revises: a428c2933249
Create Date: 2025-04-02 18:55:49.293250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '908d9365a1b4'
down_revision = 'a428c2933249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_column('email')

    # ### end Alembic commands ###
